agentignore = [
  "~tasks",
  "~links",
]

[shorthand]
"~props" = "^[^\\s:]+::"
"~tasks" = "^(TODO|DOING|LATER|NOW|CANCELED|WAITING)"
"~links" = "^\\s*(?:https?:\\/\\/\\S+|\\[[^\\]\\r\\n]+\\]\\(\\s*https?:\\/\\/[^\\s)]+(?:\\s+\"[^\"\\r\\n]*\")?\\s*\\))\\s*$"
